#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:		slave_sedes
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	slave server
# Description:		slave server
### END INIT INFO

SCRIPT="/etc/init.d/sedes"

case "$1" in
	start )
		$SCRIPT "slave" "start"
		;;
	stop )
		$SCRIPT "slave" "stop"
		;;
esac