#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:		sms_sedes
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	sms
# Description:		sms
### END INIT INFO

SCRIPT="/etc/init.d/sedes"

case "$1" in
	start )
		$SCRIPT "sms" "start"
		;;
	stop )
		$SCRIPT "sms" "stop"
		;;
esac